<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Questiontype', 'doctrine');

/**
 * BaseQuestiontype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $minanswers
 * @property integer $maxanswers
 * @property string $htmlpresentation
 * @property integer $isboolean
 * @property Doctrine_Collection $Question
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method integer             getMinanswers()       Returns the current record's "minanswers" value
 * @method integer             getMaxanswers()       Returns the current record's "maxanswers" value
 * @method string              getHtmlpresentation() Returns the current record's "htmlpresentation" value
 * @method integer             getIsboolean()        Returns the current record's "isboolean" value
 * @method Doctrine_Collection getQuestion()         Returns the current record's "Question" collection
 * @method Questiontype        setId()               Sets the current record's "id" value
 * @method Questiontype        setName()             Sets the current record's "name" value
 * @method Questiontype        setMinanswers()       Sets the current record's "minanswers" value
 * @method Questiontype        setMaxanswers()       Sets the current record's "maxanswers" value
 * @method Questiontype        setHtmlpresentation() Sets the current record's "htmlpresentation" value
 * @method Questiontype        setIsboolean()        Sets the current record's "isboolean" value
 * @method Questiontype        setQuestion()         Sets the current record's "Question" collection
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestiontype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('questiontype');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'unsigned' => false,
             'fixed' => 0,
             'length' => 30,
             ));
        $this->hasColumn('minanswers', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 1,
             ));
        $this->hasColumn('maxanswers', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 1,
             ));
        $this->hasColumn('htmlpresentation', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 250,
             ));
        $this->hasColumn('isboolean', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Question', array(
             'local' => 'id',
             'foreign' => 'Questiontype_id'));
    }
}