<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Continent', 'doctrine');

/**
 * BaseContinent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Country
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getCountry() Returns the current record's "Country" collection
 * @method Continent           setId()      Sets the current record's "id" value
 * @method Continent           setName()    Sets the current record's "name" value
 * @method Continent           setCountry() Sets the current record's "Country" collection
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContinent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('continent');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 40,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Country', array(
             'local' => 'id',
             'foreign' => 'Continent_id'));
    }
}