<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mediavideo', 'doctrine');

/**
 * BaseMediavideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $url
 * @property integer $width
 * @property integer $height
 * @property string $hovertext
 * @property integer $Exposuredata_id
 * @property Exposuredata $Exposuredata
 * @property Doctrine_Collection $Answer
 * @property Doctrine_Collection $Vote
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getUrl()             Returns the current record's "url" value
 * @method integer             getWidth()           Returns the current record's "width" value
 * @method integer             getHeight()          Returns the current record's "height" value
 * @method string              getHovertext()       Returns the current record's "hovertext" value
 * @method integer             getExposuredataId()  Returns the current record's "Exposuredata_id" value
 * @method Exposuredata        getExposuredata()    Returns the current record's "Exposuredata" value
 * @method Doctrine_Collection getAnswer()          Returns the current record's "Answer" collection
 * @method Doctrine_Collection getVote()            Returns the current record's "Vote" collection
 * @method Mediavideo          setId()              Sets the current record's "id" value
 * @method Mediavideo          setUrl()             Sets the current record's "url" value
 * @method Mediavideo          setWidth()           Sets the current record's "width" value
 * @method Mediavideo          setHeight()          Sets the current record's "height" value
 * @method Mediavideo          setHovertext()       Sets the current record's "hovertext" value
 * @method Mediavideo          setExposuredataId()  Sets the current record's "Exposuredata_id" value
 * @method Mediavideo          setExposuredata()    Sets the current record's "Exposuredata" value
 * @method Mediavideo          setAnswer()          Sets the current record's "Answer" collection
 * @method Mediavideo          setVote()            Sets the current record's "Vote" collection
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMediavideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mediavideo');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('url', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 100,
             ));
        $this->hasColumn('width', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('height', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('hovertext', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 200,
             ));
        $this->hasColumn('Exposuredata_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Exposuredata', array(
             'local' => 'Exposuredata_id',
             'foreign' => 'id'));

        $this->hasMany('Answer', array(
             'local' => 'id',
             'foreign' => 'Mediavideo_id'));

        $this->hasMany('Vote', array(
             'local' => 'id',
             'foreign' => 'Mediavideo_id'));
    }
}