<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MtmSiteusers2education', 'doctrine');

/**
 * BaseMtmSiteusers2education
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $siteusers_id
 * @property integer $education_id
 * @property Education $Education
 * @property Siteusers $Siteusers
 * 
 * @method integer                getId()           Returns the current record's "id" value
 * @method integer                getSiteusersId()  Returns the current record's "siteusers_id" value
 * @method integer                getEducationId()  Returns the current record's "education_id" value
 * @method Education              getEducation()    Returns the current record's "Education" value
 * @method Siteusers              getSiteusers()    Returns the current record's "Siteusers" value
 * @method MtmSiteusers2education setId()           Sets the current record's "id" value
 * @method MtmSiteusers2education setSiteusersId()  Sets the current record's "siteusers_id" value
 * @method MtmSiteusers2education setEducationId()  Sets the current record's "education_id" value
 * @method MtmSiteusers2education setEducation()    Sets the current record's "Education" value
 * @method MtmSiteusers2education setSiteusers()    Sets the current record's "Siteusers" value
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMtmSiteusers2education extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mtm_siteusers2education');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('siteusers_id', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 10,
             ));
        $this->hasColumn('education_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Education', array(
             'local' => 'education_id',
             'foreign' => 'id'));

        $this->hasOne('Siteusers', array(
             'local' => 'siteusers_id',
             'foreign' => 'id'));
    }
}