<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Answer', 'doctrine');

/**
 * BaseAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $text
 * @property integer $Mediapicture_id
 * @property integer $Mediavideo_id
 * @property integer $Vote_id
 * @property integer $Question_id
 * @property Mediapicture $Mediapicture
 * @property Mediavideo $Mediavideo
 * @property Vote $Vote
 * @property Question $Question
 * @property Doctrine_Collection $AnswerValues
 * @property Doctrine_Collection $answerValues
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getText()            Returns the current record's "text" value
 * @method integer             getMediapictureId()  Returns the current record's "Mediapicture_id" value
 * @method integer             getMediavideoId()    Returns the current record's "Mediavideo_id" value
 * @method integer             getVoteId()          Returns the current record's "Vote_id" value
 * @method integer             getQuestionId()      Returns the current record's "Question_id" value
 * @method Mediapicture        getMediapicture()    Returns the current record's "Mediapicture" value
 * @method Mediavideo          getMediavideo()      Returns the current record's "Mediavideo" value
 * @method Vote                getVote()            Returns the current record's "Vote" value
 * @method Question            getQuestion()        Returns the current record's "Question" value
 * @method Doctrine_Collection getAnswerValues()    Returns the current record's "AnswerValues" collection
 * @method Doctrine_Collection getAnswerValues()    Returns the current record's "answerValues" collection
 * @method Answer              setId()              Sets the current record's "id" value
 * @method Answer              setText()            Sets the current record's "text" value
 * @method Answer              setMediapictureId()  Sets the current record's "Mediapicture_id" value
 * @method Answer              setMediavideoId()    Sets the current record's "Mediavideo_id" value
 * @method Answer              setVoteId()          Sets the current record's "Vote_id" value
 * @method Answer              setQuestionId()      Sets the current record's "Question_id" value
 * @method Answer              setMediapicture()    Sets the current record's "Mediapicture" value
 * @method Answer              setMediavideo()      Sets the current record's "Mediavideo" value
 * @method Answer              setVote()            Sets the current record's "Vote" value
 * @method Answer              setQuestion()        Sets the current record's "Question" value
 * @method Answer              setAnswerValues()    Sets the current record's "AnswerValues" collection
 * @method Answer              setAnswerValues()    Sets the current record's "answerValues" collection
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('answer');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('text', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 100,
             ));
        $this->hasColumn('Mediapicture_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('Mediavideo_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('Vote_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('Question_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mediapicture', array(
             'local' => 'Mediapicture_id',
             'foreign' => 'id'));

        $this->hasOne('Mediavideo', array(
             'local' => 'Mediavideo_id',
             'foreign' => 'id'));

        $this->hasOne('Vote', array(
             'local' => 'Vote_id',
             'foreign' => 'id'));

        $this->hasOne('Question', array(
             'local' => 'Question_id',
             'foreign' => 'id'));

        $this->hasMany('Answervalue as AnswerValues', array(
             'refClass' => 'MtmAnswer2answervalue',
             'local' => 'answer_id',
             'foreign' => 'answervalue_id'));

        $this->hasMany('MtmAnswer2answervalue as answerValues', array(
             'local' => 'id',
             'foreign' => 'answer_id'));
    }
}