<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MtmSiteusers2answervalue', 'doctrine');

/**
 * BaseMtmSiteusers2answervalue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $answervalue_id
 * @property Answervalue $Answervalue
 * @property Siteusers $Siteusers
 * 
 * @method integer                  getId()             Returns the current record's "id" value
 * @method integer                  getUserId()         Returns the current record's "user_id" value
 * @method integer                  getAnswervalueId()  Returns the current record's "answervalue_id" value
 * @method Answervalue              getAnswervalue()    Returns the current record's "Answervalue" value
 * @method Siteusers                getSiteusers()      Returns the current record's "Siteusers" value
 * @method MtmSiteusers2answervalue setId()             Sets the current record's "id" value
 * @method MtmSiteusers2answervalue setUserId()         Sets the current record's "user_id" value
 * @method MtmSiteusers2answervalue setAnswervalueId()  Sets the current record's "answervalue_id" value
 * @method MtmSiteusers2answervalue setAnswervalue()    Sets the current record's "Answervalue" value
 * @method MtmSiteusers2answervalue setSiteusers()      Sets the current record's "Siteusers" value
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMtmSiteusers2answervalue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mtm_siteusers2answervalue');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 10,
             ));
        $this->hasColumn('answervalue_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Answervalue', array(
             'local' => 'answervalue_id',
             'foreign' => 'id'));

        $this->hasOne('Siteusers', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}