<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Fangroup', 'doctrine');

/**
 * BaseFangroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $agerangestart
 * @property integer $agerangeend
 * @property string $gender
 * @property string $homepage
 * @property integer $Team_id
 * @property integer $Address_id
 * @property integer $Mediapicture_id
 * @property Team $Team
 * @property Address $Address
 * @property Mediapicture $Mediapicture
 * @property Doctrine_Collection $Segments
 * @property Doctrine_Collection $SiteUsers
 * @property Doctrine_Collection $MtmFangroup2siteusers
 * @property Doctrine_Collection $MtmSegment2fangroup
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method integer             getAgerangestart()         Returns the current record's "agerangestart" value
 * @method integer             getAgerangeend()           Returns the current record's "agerangeend" value
 * @method string              getGender()                Returns the current record's "gender" value
 * @method string              getHomepage()              Returns the current record's "homepage" value
 * @method integer             getTeamId()                Returns the current record's "Team_id" value
 * @method integer             getAddressId()             Returns the current record's "Address_id" value
 * @method integer             getMediapictureId()        Returns the current record's "Mediapicture_id" value
 * @method Team                getTeam()                  Returns the current record's "Team" value
 * @method Address             getAddress()               Returns the current record's "Address" value
 * @method Mediapicture        getMediapicture()          Returns the current record's "Mediapicture" value
 * @method Doctrine_Collection getSegments()              Returns the current record's "Segments" collection
 * @method Doctrine_Collection getSiteUsers()             Returns the current record's "SiteUsers" collection
 * @method Doctrine_Collection getMtmFangroup2siteusers() Returns the current record's "MtmFangroup2siteusers" collection
 * @method Doctrine_Collection getMtmSegment2fangroup()   Returns the current record's "MtmSegment2fangroup" collection
 * @method Fangroup            setId()                    Sets the current record's "id" value
 * @method Fangroup            setName()                  Sets the current record's "name" value
 * @method Fangroup            setAgerangestart()         Sets the current record's "agerangestart" value
 * @method Fangroup            setAgerangeend()           Sets the current record's "agerangeend" value
 * @method Fangroup            setGender()                Sets the current record's "gender" value
 * @method Fangroup            setHomepage()              Sets the current record's "homepage" value
 * @method Fangroup            setTeamId()                Sets the current record's "Team_id" value
 * @method Fangroup            setAddressId()             Sets the current record's "Address_id" value
 * @method Fangroup            setMediapictureId()        Sets the current record's "Mediapicture_id" value
 * @method Fangroup            setTeam()                  Sets the current record's "Team" value
 * @method Fangroup            setAddress()               Sets the current record's "Address" value
 * @method Fangroup            setMediapicture()          Sets the current record's "Mediapicture" value
 * @method Fangroup            setSegments()              Sets the current record's "Segments" collection
 * @method Fangroup            setSiteUsers()             Sets the current record's "SiteUsers" collection
 * @method Fangroup            setMtmFangroup2siteusers() Sets the current record's "MtmFangroup2siteusers" collection
 * @method Fangroup            setMtmSegment2fangroup()   Sets the current record's "MtmSegment2fangroup" collection
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFangroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fangroup');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 255,
             ));
        $this->hasColumn('agerangestart', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('agerangeend', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('gender', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 10,
             ));
        $this->hasColumn('homepage', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 255,
             ));
        $this->hasColumn('Team_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('Address_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('Mediapicture_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team', array(
             'local' => 'Team_id',
             'foreign' => 'id'));

        $this->hasOne('Address', array(
             'local' => 'Address_id',
             'foreign' => 'id'));

        $this->hasOne('Mediapicture', array(
             'local' => 'Mediapicture_id',
             'foreign' => 'id'));

        $this->hasMany('Segment as Segments', array(
             'refClass' => 'MtmSegment2fangroup',
             'local' => 'fangroup_id',
             'foreign' => 'segment_id'));

        $this->hasMany('Siteusers as SiteUsers', array(
             'refClass' => 'MtmFangroup2siteusers',
             'local' => 'fangroup_id',
             'foreign' => 'siteuser_id'));

        $this->hasMany('MtmFangroup2siteusers', array(
             'local' => 'id',
             'foreign' => 'fangroup_id'));

        $this->hasMany('MtmSegment2fangroup', array(
             'local' => 'id',
             'foreign' => 'fangroup_id'));
    }
}