<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Priviclass', 'doctrine');

/**
 * BasePriviclass
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $level
 * @property Doctrine_Collection $Siteusers
 * @property Doctrine_Collection $Teamsiteusersaddnlinfo
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getName()                   Returns the current record's "name" value
 * @method integer             getLevel()                  Returns the current record's "level" value
 * @method Doctrine_Collection getSiteusers()              Returns the current record's "Siteusers" collection
 * @method Doctrine_Collection getTeamsiteusersaddnlinfo() Returns the current record's "Teamsiteusersaddnlinfo" collection
 * @method Priviclass          setId()                     Sets the current record's "id" value
 * @method Priviclass          setName()                   Sets the current record's "name" value
 * @method Priviclass          setLevel()                  Sets the current record's "level" value
 * @method Priviclass          setSiteusers()              Sets the current record's "Siteusers" collection
 * @method Priviclass          setTeamsiteusersaddnlinfo() Sets the current record's "Teamsiteusersaddnlinfo" collection
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePriviclass extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('priviclass');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 50,
             ));
        $this->hasColumn('level', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Siteusers', array(
             'local' => 'id',
             'foreign' => 'Priviclass_id'));

        $this->hasMany('Teamsiteusersaddnlinfo', array(
             'local' => 'id',
             'foreign' => 'Priviclass_id'));
    }
}