<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Work', 'doctrine');

/**
 * BaseWork
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $position
 * @property string $citytown
 * @property string $description
 * @property timestamp $timeperiod
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getPosition()    Returns the current record's "position" value
 * @method string    getCitytown()    Returns the current record's "citytown" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method timestamp getTimeperiod()  Returns the current record's "timeperiod" value
 * @method Work      setId()          Sets the current record's "id" value
 * @method Work      setPosition()    Sets the current record's "position" value
 * @method Work      setCitytown()    Sets the current record's "citytown" value
 * @method Work      setDescription() Sets the current record's "description" value
 * @method Work      setTimeperiod()  Sets the current record's "timeperiod" value
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWork extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('work');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('position', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 255,
             ));
        $this->hasColumn('citytown', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 255,
             ));
        $this->hasColumn('timeperiod', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}