<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Sporttype', 'doctrine');

/**
 * BaseSporttype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Team
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getTeam()        Returns the current record's "Team" collection
 * @method Sporttype           setId()          Sets the current record's "id" value
 * @method Sporttype           setName()        Sets the current record's "name" value
 * @method Sporttype           setDescription() Sets the current record's "description" value
 * @method Sporttype           setTeam()        Sets the current record's "Team" collection
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSporttype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sporttype');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Team', array(
             'local' => 'id',
             'foreign' => 'Sporttype_id'));
    }
}