<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Country', 'doctrine');

/**
 * BaseCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $Continent_id
 * @property Continent $Continent
 * @property Doctrine_Collection $City
 * @property Doctrine_Collection $State
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getContinentId()  Returns the current record's "Continent_id" value
 * @method Continent           getContinent()    Returns the current record's "Continent" value
 * @method Doctrine_Collection getCity()         Returns the current record's "City" collection
 * @method Doctrine_Collection getState()        Returns the current record's "State" collection
 * @method Country             setId()           Sets the current record's "id" value
 * @method Country             setName()         Sets the current record's "name" value
 * @method Country             setContinentId()  Sets the current record's "Continent_id" value
 * @method Country             setContinent()    Sets the current record's "Continent" value
 * @method Country             setCity()         Sets the current record's "City" collection
 * @method Country             setState()        Sets the current record's "State" collection
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('country');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 200,
             ));
        $this->hasColumn('Continent_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Continent', array(
             'local' => 'Continent_id',
             'foreign' => 'id'));

        $this->hasMany('City', array(
             'local' => 'id',
             'foreign' => 'Country_id'));

        $this->hasMany('State', array(
             'local' => 'id',
             'foreign' => 'Country_id'));
    }
}