<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Exposuredata', 'doctrine');

/**
 * BaseExposuredata
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $totalexposures
 * @property timestamp $firstexposuredate
 * @property timestamp $lastexposuredate
 * @property Doctrine_Collection $Mediapicture
 * @property Doctrine_Collection $Mediavideo
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getTotalexposures()    Returns the current record's "totalexposures" value
 * @method timestamp           getFirstexposuredate() Returns the current record's "firstexposuredate" value
 * @method timestamp           getLastexposuredate()  Returns the current record's "lastexposuredate" value
 * @method Doctrine_Collection getMediapicture()      Returns the current record's "Mediapicture" collection
 * @method Doctrine_Collection getMediavideo()        Returns the current record's "Mediavideo" collection
 * @method Exposuredata        setId()                Sets the current record's "id" value
 * @method Exposuredata        setTotalexposures()    Sets the current record's "totalexposures" value
 * @method Exposuredata        setFirstexposuredate() Sets the current record's "firstexposuredate" value
 * @method Exposuredata        setLastexposuredate()  Sets the current record's "lastexposuredate" value
 * @method Exposuredata        setMediapicture()      Sets the current record's "Mediapicture" collection
 * @method Exposuredata        setMediavideo()        Sets the current record's "Mediavideo" collection
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExposuredata extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exposuredata');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('totalexposures', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('firstexposuredate', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 25,
             ));
        $this->hasColumn('lastexposuredate', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Mediapicture', array(
             'local' => 'id',
             'foreign' => 'Exposuredata_id'));

        $this->hasMany('Mediavideo', array(
             'local' => 'id',
             'foreign' => 'Exposuredata_id'));
    }
}