<?php

/**
 * BaseGender
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Segment
 * @property Doctrine_Collection $Siteusers
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getSegment()   Returns the current record's "Segment" collection
 * @method Doctrine_Collection getSiteusers() Returns the current record's "Siteusers" collection
 * @method Gender              setId()        Sets the current record's "id" value
 * @method Gender              setName()      Sets the current record's "name" value
 * @method Gender              setSegment()   Sets the current record's "Segment" collection
 * @method Gender              setSiteusers() Sets the current record's "Siteusers" collection
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGender extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gender');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Segment', array(
             'local' => 'id',
             'foreign' => 'Gender_id'));

        $this->hasMany('Siteusers', array(
             'local' => 'id',
             'foreign' => 'Gender_id'));
    }
}