<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('League', 'doctrine');

/**
 * BaseLeague
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $Address_id
 * @property Address $Address
 * @property Doctrine_Collection $Team
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getAddressId()  Returns the current record's "Address_id" value
 * @method Address             getAddress()    Returns the current record's "Address" value
 * @method Doctrine_Collection getTeam()       Returns the current record's "Team" collection
 * @method League              setId()         Sets the current record's "id" value
 * @method League              setName()       Sets the current record's "name" value
 * @method League              setAddressId()  Sets the current record's "Address_id" value
 * @method League              setAddress()    Sets the current record's "Address" value
 * @method League              setTeam()       Sets the current record's "Team" collection
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeague extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('league');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 255,
             ));
        $this->hasColumn('Address_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Address', array(
             'local' => 'Address_id',
             'foreign' => 'id'));

        $this->hasMany('Team', array(
             'local' => 'id',
             'foreign' => 'League_id'));
    }
}