<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MtmSegment2address', 'doctrine');

/**
 * BaseMtmSegment2address
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $segment_id
 * @property integer $address_id
 * @property Address $Address
 * @property Segment $Segment
 * 
 * @method integer            getId()         Returns the current record's "id" value
 * @method integer            getSegmentId()  Returns the current record's "segment_id" value
 * @method integer            getAddressId()  Returns the current record's "address_id" value
 * @method Address            getAddress()    Returns the current record's "Address" value
 * @method Segment            getSegment()    Returns the current record's "Segment" value
 * @method MtmSegment2address setId()         Sets the current record's "id" value
 * @method MtmSegment2address setSegmentId()  Sets the current record's "segment_id" value
 * @method MtmSegment2address setAddressId()  Sets the current record's "address_id" value
 * @method MtmSegment2address setAddress()    Sets the current record's "Address" value
 * @method MtmSegment2address setSegment()    Sets the current record's "Segment" value
 * 
 * @package    PhpProject2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMtmSegment2address extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mtm_segment2address');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('segment_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
        $this->hasColumn('address_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             'fixed' => 0,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Address', array(
             'local' => 'address_id',
             'foreign' => 'id'));

        $this->hasOne('Segment', array(
             'local' => 'segment_id',
             'foreign' => 'id'));
    }
}