<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/17 18:52:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=fanarchydb',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
