<?php

/**
 * AnswervalueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnswervalueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnswervalueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Answervalue');
    }
}