<?php

/**
 * ContinentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContinentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContinentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Continent');
    }
}