<?php

/**
 * EducationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EducationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EducationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Education');
    }
}