<?php

/**
 * ExposuredataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExposuredataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExposuredataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Exposuredata');
    }
}