<?php

/**
 * GenderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GenderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GenderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gender');
    }
}