<?php

/**
 * MediapictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MediapictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MediapictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mediapicture');
    }
}