<?php

/**
 * MediavideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MediavideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MediavideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mediavideo');
    }
}