<?php

/**
 * MtmAnswer2answervalueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MtmAnswer2answervalueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MtmAnswer2answervalueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MtmAnswer2answervalue');
    }
}