<?php

/**
 * MtmFangroup2siteusersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MtmFangroup2siteusersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MtmFangroup2siteusersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MtmFangroup2siteusers');
    }
}