<?php

/**
 * MtmSiteusers2educationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MtmSiteusers2educationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MtmSiteusers2educationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MtmSiteusers2education');
    }
}