<?php

/**
 * MtmSegment2addressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MtmSegment2addressTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MtmSegment2addressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MtmSegment2address');
    }
}