<?php

/**
 * MtmSiteusers2answervalueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MtmSiteusers2answervalueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MtmSiteusers2answervalueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MtmSiteusers2answervalue');
    }
}