<?php

/**
 * MtmSegment2fangroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MtmSegment2fangroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MtmSegment2fangroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MtmSegment2fangroup');
    }
}