<?php

/**
 * MtmSiteusers2teamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MtmSiteusers2teamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MtmSiteusers2teamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MtmSiteusers2team');
    }
}