<?php

/**
 * PaymentRegisterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentRegisterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaymentRegisterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaymentRegister');
    }
}