<?php

/**
 * PPITable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PPITable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PPITable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PPI');
    }
}