<?php

/**
 * PriviclassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PriviclassTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PriviclassTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Priviclass');
    }
}