<?php

/**
 * QuestiontypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestiontypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuestiontypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Questiontype');
    }
}