<?php

/**
 * SitevarsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SitevarsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SitevarsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sitevars');
    }
}