<?php

/**
 * SiteusersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteusersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteusersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Siteusers');
    }
}