<?php

/**
 * SporttypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SporttypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SporttypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sporttype');
    }
}