<?php

/**
 * TeamsiteusersaddnlinfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamsiteusersaddnlinfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamsiteusersaddnlinfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Teamsiteusersaddnlinfo');
    }
}