<?php

/**
 * VoteinstanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VoteinstanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VoteinstanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Voteinstance');
    }
}