<?php

/**
 * WorkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Work');
    }
}